[package]
name = "mqtt2exmebus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#paho-mqtt = { git = "https://github.com/eclipse/paho.mqtt.rust.git", branch = "master" }
paho-mqtt = { git = "https://github.com/eclipse/paho.mqtt.rust.git", branch = "master", default-features=false, features=["bundled"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
to_vec = "0.1.0"
bincode = "1.3.3"
futures = "0.3.25"
env_logger = "0.9.1"
async-std = "1.12.0"
[dependencies.uuid]
version = "1.2.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
